### ISSUE TITLE
Undefined behavior with UnitTests on Linux x86_64

### ISSUE THREAD

**Issue by Megaxela** [louis-langholtz/PlayRho#36]
Undefined behaviour on archlinux x86_64. 
Built with `cmake -DPLAYRHO_BUILD_TESTBED=On -DPLAYRHO_BUILD_UNIT_TESTS=On -DPLAYRHO_INSTALL=On  .. && make -j8`
![image](https://user-images.githubusercontent.com/1456504/29129218-c042b6fc-7d2e-11e7-886a-f5e81c46ba7d.png)

![image](https://user-images.githubusercontent.com/1456504/29129267-e413bf5e-7d2e-11e7-80ac-52a937e5fadd.png)

![image](https://user-images.githubusercontent.com/1456504/29129659-353ee9c0-7d30-11e7-9cad-a8534ccbcbae.png)

### Expected/Desired Behavior or Experience:
All tests has to complete fine.

### Actual Behavior:
Tests can't even be completed.

### Steps to Reproduce the Actual Behavior:
I just built project and started to run tests. I run them for 3 times to get `stack smashing`.

**Comment by louis-langholtz** [comment]
Thank you for reporting this!

Off the top of your head, do you have any idea/suspicion why these unit test failures don't show up on the Travis-CI build & runs for the linux platform? What compiler are you building with? And what version/release is it?

While I await any more insights you may have, I'll review the relevant code.

Thanks again.

**Comment by louis-langholtz** [comment]
Ok... I'm guessing you've turned on additional checking of some sort. Awesome!

Turns out that the `Vec2.InvalidIndex` test is indeed testing undefined behavior and indeed accessing memory it shouldn't be. Sorry about that. I'll have a fix for this shortly.

Haven't looked yet into the other unit tests that are failing. I'll get to that after getting the previously mentioned fix in.

**Comment by louis-langholtz** [comment]
Thank you for the update.

Curious that the exceptions aren't seen now. Maybe those were related to the memory mayhem.

I haven't had the chance to test with GCC 7.1.1 yet so it's extra helpful that you're doing that.

Out of curiosity, are you doing a debug build or a release build? I ask because the StackAllocator.slower_than_mallocfree unit test is a bit of a benchmark test too and is therefore reliant on optimizations being turned on (as more common with release builds).

Also, can you see if there's any warning messages that the compiler is emitting during the build phase? If there's any warnings, please let me know what they are.

Odd that the `MassData.GetForCenteredEdge` is getting such a differing result from what the test is expecting. Looks like the `MultiShape.AddConvexHullWithTwoPointsSameAsEdge` is also reporting a mass related issue. I'll update the latter test first I think to make it output more easily recognizable data in terms of what the difference is.

Probably gonna be tomorrow when I get to tackle this more.

**Comment by Megaxela** [comment]
Well, sometimes I still see some exceptions.
![image](https://user-images.githubusercontent.com/1456504/29170729-8c2948f4-7de2-11e7-992d-f2c6612840e4.png)

And I have not taking any warning during building.

**Comment by louis-langholtz** [comment]
By *sometimes seeing exceptions* do you mean that on one run of the unit tests with the latest code that you'll not see any of these exception messages while on another run with the same code you will see them?

I don't think these failures should occur unreliably unless there's more corruption/undefined-behavior going on.

Incidentally, the version of GCC used in the Travis-CI build is GCC 6.3.0. The unit tests that are run on Travis-CI aren't failing with GCC 6.3.0 so if you need a quick work-around you might try building with 6.3.0 and for release mode (instead of 7.1.1) and see if the same unit tests still fail (they shouldn't though unless there's smoother relevant difference).

**Comment by Megaxela** [comment]
Ye, I meant that in different runs I'm taking different results. Sometimes I'm getting exceptions, sometime dont.

Ok then , I guess we'll need to wait for some `gcc` updates. Maybe it will fix this behaviour.

**Comment by louis-langholtz** [comment]
Found a helpful signal:

Using `clang` 4.0, the [Travis-CI build](https://travis-ci.org/louis-langholtz/PlayRho/jobs/263316968) gets to the `ChainShape.TwoVertexLikeEdge` unit test and outputs the following (and then ends):
```
[ RUN      ] ChainShape.TwoVertexLikeEdge
terminate called after throwing an instance of 'playrho::InvalidArgument'
  what():  BoundedValue: value not >= 0
```

This seems like some of the behavior you've identified with `gcc` 7.1.1. So I don't think `gcc` 7.1.1 has any fault in this.

BTW, the `playrho::InvalidArgument` exception is what is expected to be thrown for a `BoundedValue` that's constructed with or assigned a value that's not allowed within its accepted range. Seemingly one of the `NonNegative` bounded values employed in the `ChainShape.TwoVertexLikeEdge` code path is being set invalidly.

**Comment by louis-langholtz** [comment]
I believe (and hope) that this is all fixed now as of commit ee1f32464ad659716b0d2b434a4da478ace6650e.

If you pull this latest code, please confirm whether or not the unit tests show any more undefined behavior like problems.

I'm closing this issue under my assumption that this is indeed fixed now. Let's re-open this if that's incorrect.

And thank you again for your help and patience with this!

**Comment by Megaxela** [comment]
Thank you for fixes. They are working like a charm. But I'm still getting 1 failed test.
I built PlayRho with `-DCMAKE_BUILD_TYPE=Release`. But `StackAllocator.slower_than_mallocfree` test still failed. I guess I'll create new one issue for this.
